#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_WORD_LENGTH 31
#define MAX_FILENAME_SIZE 40 //24?
#define MAX_FSIZE_SIZE 10
#define MAX_READ_SIZE 128
#define MAX_PLID_SIZE 6
#define MAX_COMMAND_SIZE 3
#define MAX_PLAYER_STATE_SIZE 37
#define MAX_FILE_SIZE 1024^3
#define TIMEOUT 5000

#endif